-- MySQL Script generated by MySQL Workbench
-- Mon Oct 24 17:23:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema repositorio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `repositorio` ;

-- -----------------------------------------------------
-- Schema repositorio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `repositorio` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `repositorio` ;

-- -----------------------------------------------------
-- Table `areas_de_conhecimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `areas_de_conhecimento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `areas_de_conhecimento` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `instituicao_cod` INT UNSIGNED NOT NULL,
  `area_de_conhecimento` VARCHAR(255) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `curso` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `instituicao_cod` INT UNSIGNED NOT NULL,
  `curso` VARCHAR(255) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituicao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `instituicao` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_completo` TEXT NULL,
  `cnpj` VARCHAR(45) NULL,
  `endereço` TEXT NULL,
  `teletone` VARCHAR(45) NULL,
  `email` VARCHAR(150) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `publicacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `publicacao` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `instituicao_cod` INT UNSIGNED NOT NULL,
  `areas_de_conhecimento_cod` INT UNSIGNED NOT NULL,
  `turma_cod` INT UNSIGNED NOT NULL,
  `titulo` TEXT NULL,
  `autor` VARCHAR(255) NULL,
  `orientador` VARCHAR(255) NULL,
  `membro_1` VARCHAR(255) NULL,
  `membro_2` VARCHAR(255) NULL,
  `membro_3` VARCHAR(255) NULL,
  `palavras_chave` VARCHAR(255) NULL,
  `data` DATE NULL,
  `referencia` TEXT NULL,
  `resumo` TEXT NULL,
  `abstract` TEXT NULL,
  `url` TEXT NULL,
  `arquivo` VARCHAR(255) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turma` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `turma` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `instituicao_cod` INT UNSIGNED NOT NULL,
  `curso_cod` INT UNSIGNED NOT NULL,
  `turma` VARCHAR(45) NULL,
  `ano` VARCHAR(45) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `instituicao_cod` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `senha` VARCHAR(64) NULL,
  `nivel` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `curso`
-- -----------------------------------------------------
START TRANSACTION;
USE `repositorio`;
INSERT INTO `curso` (`cod`, `instituicao_cod`, `curso`) VALUES (1, 1, 'Ciências Biológicas');
INSERT INTO `curso` (`cod`, `instituicao_cod`, `curso`) VALUES (2, 1, 'Engenharia Agronômica');
INSERT INTO `curso` (`cod`, `instituicao_cod`, `curso`) VALUES (3, 1, 'Engenharia Ambiental e Sanitária');
INSERT INTO `curso` (`cod`, `instituicao_cod`, `curso`) VALUES (4, 1, 'Tecnologia em Análise e Desenvolvimento de Sistemas');

COMMIT;


-- -----------------------------------------------------
-- Data for table `instituicao`
-- -----------------------------------------------------
START TRANSACTION;
USE `repositorio`;
INSERT INTO `instituicao` (`cod`, `nome_completo`, `cnpj`, `endereço`, `teletone`, `email`) VALUES (1, 'IFPA - Campus Itaituba', '10.763.998/0012-92.', 'R. Universitário, s/n - Maria Magdalena, Itaituba - PA, 68183-300', '(93) 99172-8860', 'itaituba@ifpa.edu.br');

COMMIT;


-- -----------------------------------------------------
-- Data for table `usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `repositorio`;
INSERT INTO `usuario` (`cod`, `instituicao_cod`, `nome`, `email`, `senha`, `nivel`, `status`) VALUES (1, 1, 'Joab Alencar', 'joabtorres1508@gmail.com', 'SHA1(MD5(\'prodepa\'))', 2, 1);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
